export const config = {
    RPC_URL: 'https://rpc.rebus.nodestake.top',
    REST_URL: 'https://api.rebus.nodestake.top',
    EXPLORER_URL: 'https://rebus.explorers.guru',
    NETWORK_NAME: 'Rebus',
    NETWORK_TYPE: 'mainnet',
    CHAIN_ID: 'reb_1111-1',
    CHAIN_NAME: 'Rebus',
    COIN_DENOM: 'rebus',
    COIN_MINIMAL_DENOM: 'AREBUS',
    COIN_DECIMALS: 6,
    PREFIX: 'stars',
    COIN_TYPE: 118,
    COINGECKO_ID: 'rebus',
    DEFAULT_GAS: 250000,
    GAS_PRICE_STEP_LOW: 0.0,
    GAS_PRICE_STEP_AVERAGE: 0.0,
    GAS_PRICE_STEP_HIGH: 0.025,
    FEATURES: ['stargate', 'ibc-transfer', 'no-legacy-stdTx'],
};
